name: Build JSON Schema

on:
  pull_request:
    paths:
      - "types/workflowConfig.types.ts"
      - "constants/json-schema-meta.ts"

jobs:
  generate-json-schema:
    runs-on: ubuntu-latest
    name: Generate JSON Schema
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun ci
      - name: Run JSON Schema generation
        run: bun generate-json-schema
      - name: Check for changes
        id: verify-changed-files
        run: |
          if [ -n "$(git status --porcelain schemas/json/symphony.json)" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        if: steps.verify-changed-files.outputs.changed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add schemas/json/symphony.json
          git commit -m "feat(schema): auto-generate json schema"
          git push
